server:
  port: 8761

spring:
  application:
    name: serviceregistry

eureka:
#  server:
#    enable-self-preservation: false
#    expected-client-renewal-interval-seconds: 3
#    eviction-timer-interval-in-ms: 2000
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false